// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: protos/actors/verifier/verifier.proto

package verifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vp string `protobuf:"bytes,1,opt,name=vp,proto3" json:"vp,omitempty"`
}

func (x *VPReq) Reset() {
	*x = VPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_actors_verifier_verifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPReq) ProtoMessage() {}

func (x *VPReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_actors_verifier_verifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPReq.ProtoReflect.Descriptor instead.
func (*VPReq) Descriptor() ([]byte, []int) {
	return file_protos_actors_verifier_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *VPReq) GetVp() string {
	if x != nil {
		return x.Vp
	}
	return ""
}

type VPRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *VPRes) Reset() {
	*x = VPRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_actors_verifier_verifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VPRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPRes) ProtoMessage() {}

func (x *VPRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_actors_verifier_verifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPRes.ProtoReflect.Descriptor instead.
func (*VPRes) Descriptor() ([]byte, []int) {
	return file_protos_actors_verifier_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *VPRes) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_protos_actors_verifier_verifier_proto protoreflect.FileDescriptor

var file_protos_actors_verifier_verifier_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x05, 0x56, 0x50, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76,
	0x70, 0x22, 0x1d, 0x0a, 0x05, 0x56, 0x50, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x32, 0x4d, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x56, 0x50, 0x12,
	0x16, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x56, 0x50, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x56, 0x50, 0x52, 0x65, 0x73, 0x42,
	0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61,
	0x6d, 0x39, 0x6e, 0x69, 0x6e, 0x65, 0x2f, 0x53, 0x53, 0x49, 0x5f, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_actors_verifier_verifier_proto_rawDescOnce sync.Once
	file_protos_actors_verifier_verifier_proto_rawDescData = file_protos_actors_verifier_verifier_proto_rawDesc
)

func file_protos_actors_verifier_verifier_proto_rawDescGZIP() []byte {
	file_protos_actors_verifier_verifier_proto_rawDescOnce.Do(func() {
		file_protos_actors_verifier_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_actors_verifier_verifier_proto_rawDescData)
	})
	return file_protos_actors_verifier_verifier_proto_rawDescData
}

var file_protos_actors_verifier_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_actors_verifier_verifier_proto_goTypes = []interface{}{
	(*VPReq)(nil), // 0: actors.verifier.VPReq
	(*VPRes)(nil), // 1: actors.verifier.VPRes
}
var file_protos_actors_verifier_verifier_proto_depIdxs = []int32{
	0, // 0: actors.verifier.VerifierService.VerifyVP:input_type -> actors.verifier.VPReq
	1, // 1: actors.verifier.VerifierService.VerifyVP:output_type -> actors.verifier.VPRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_actors_verifier_verifier_proto_init() }
func file_protos_actors_verifier_verifier_proto_init() {
	if File_protos_actors_verifier_verifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_actors_verifier_verifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_actors_verifier_verifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VPRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_actors_verifier_verifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_actors_verifier_verifier_proto_goTypes,
		DependencyIndexes: file_protos_actors_verifier_verifier_proto_depIdxs,
		MessageInfos:      file_protos_actors_verifier_verifier_proto_msgTypes,
	}.Build()
	File_protos_actors_verifier_verifier_proto = out.File
	file_protos_actors_verifier_verifier_proto_rawDesc = nil
	file_protos_actors_verifier_verifier_proto_goTypes = nil
	file_protos_actors_verifier_verifier_proto_depIdxs = nil
}
