// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: protos/actors/verifier/verifier.proto

package verifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerifierServiceClient is the client API for VerifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifierServiceClient interface {
	VerifyVP(ctx context.Context, in *VPReq, opts ...grpc.CallOption) (*VPRes, error)
}

type verifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierServiceClient(cc grpc.ClientConnInterface) VerifierServiceClient {
	return &verifierServiceClient{cc}
}

func (c *verifierServiceClient) VerifyVP(ctx context.Context, in *VPReq, opts ...grpc.CallOption) (*VPRes, error) {
	out := new(VPRes)
	err := c.cc.Invoke(ctx, "/actors.verifier.VerifierService/VerifyVP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServiceServer is the server API for VerifierService service.
// All implementations must embed UnimplementedVerifierServiceServer
// for forward compatibility
type VerifierServiceServer interface {
	VerifyVP(context.Context, *VPReq) (*VPRes, error)
	mustEmbedUnimplementedVerifierServiceServer()
}

// UnimplementedVerifierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVerifierServiceServer struct {
}

func (UnimplementedVerifierServiceServer) VerifyVP(context.Context, *VPReq) (*VPRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyVP not implemented")
}
func (UnimplementedVerifierServiceServer) mustEmbedUnimplementedVerifierServiceServer() {}

// UnsafeVerifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierServiceServer will
// result in compilation errors.
type UnsafeVerifierServiceServer interface {
	mustEmbedUnimplementedVerifierServiceServer()
}

func RegisterVerifierServiceServer(s grpc.ServiceRegistrar, srv VerifierServiceServer) {
	s.RegisterService(&VerifierService_ServiceDesc, srv)
}

func _VerifierService_VerifyVP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServiceServer).VerifyVP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/actors.verifier.VerifierService/VerifyVP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServiceServer).VerifyVP(ctx, req.(*VPReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifierService_ServiceDesc is the grpc.ServiceDesc for VerifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "actors.verifier.VerifierService",
	HandlerType: (*VerifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyVP",
			Handler:    _VerifierService_VerifyVP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/actors/verifier/verifier.proto",
}
