// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: protos/vdr/resolver/resolver.proto

package resolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_UNKNOWN State = 0
	State_SUCCESS State = 1
	State_FAILURE State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
	}
	State_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILURE": 2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vdr_resolver_resolver_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_protos_vdr_resolver_resolver_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_protos_vdr_resolver_resolver_proto_rawDescGZIP(), []int{0}
}

type ResolveDIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ResolveDIDReq) Reset() {
	*x = ResolveDIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vdr_resolver_resolver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveDIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDIDReq) ProtoMessage() {}

func (x *ResolveDIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vdr_resolver_resolver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDIDReq.ProtoReflect.Descriptor instead.
func (*ResolveDIDReq) Descriptor() ([]byte, []int) {
	return file_protos_vdr_resolver_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveDIDReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type ResolveDIDRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DidDoc string `protobuf:"bytes,1,opt,name=didDoc,proto3" json:"didDoc,omitempty"`
	State  State  `protobuf:"varint,2,opt,name=state,proto3,enum=vdr.resolver.State" json:"state,omitempty"`
}

func (x *ResolveDIDRes) Reset() {
	*x = ResolveDIDRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vdr_resolver_resolver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveDIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDIDRes) ProtoMessage() {}

func (x *ResolveDIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vdr_resolver_resolver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDIDRes.ProtoReflect.Descriptor instead.
func (*ResolveDIDRes) Descriptor() ([]byte, []int) {
	return file_protos_vdr_resolver_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveDIDRes) GetDidDoc() string {
	if x != nil {
		return x.DidDoc
	}
	return ""
}

func (x *ResolveDIDRes) GetState() State {
	if x != nil {
		return x.State
	}
	return State_UNKNOWN
}

var File_protos_vdr_resolver_resolver_proto protoreflect.FileDescriptor

var file_protos_vdr_resolver_resolver_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x64, 0x72, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x76, 0x64, 0x72, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x22, 0x21, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x44, 0x49, 0x44, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x64, 0x44, 0x6f, 0x63, 0x12, 0x29,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x76, 0x64, 0x72, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x2e, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x02, 0x32, 0x55, 0x0a, 0x0b, 0x44, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x76, 0x64, 0x72, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x76, 0x64, 0x72, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x44, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x61, 0x6d, 0x39, 0x6e, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76,
	0x64, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_vdr_resolver_resolver_proto_rawDescOnce sync.Once
	file_protos_vdr_resolver_resolver_proto_rawDescData = file_protos_vdr_resolver_resolver_proto_rawDesc
)

func file_protos_vdr_resolver_resolver_proto_rawDescGZIP() []byte {
	file_protos_vdr_resolver_resolver_proto_rawDescOnce.Do(func() {
		file_protos_vdr_resolver_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vdr_resolver_resolver_proto_rawDescData)
	})
	return file_protos_vdr_resolver_resolver_proto_rawDescData
}

var file_protos_vdr_resolver_resolver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_vdr_resolver_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_vdr_resolver_resolver_proto_goTypes = []interface{}{
	(State)(0),            // 0: vdr.resolver.State
	(*ResolveDIDReq)(nil), // 1: vdr.resolver.ResolveDIDReq
	(*ResolveDIDRes)(nil), // 2: vdr.resolver.ResolveDIDRes
}
var file_protos_vdr_resolver_resolver_proto_depIdxs = []int32{
	0, // 0: vdr.resolver.ResolveDIDRes.state:type_name -> vdr.resolver.State
	1, // 1: vdr.resolver.DIDResolver.ResolveDID:input_type -> vdr.resolver.ResolveDIDReq
	2, // 2: vdr.resolver.DIDResolver.ResolveDID:output_type -> vdr.resolver.ResolveDIDRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_vdr_resolver_resolver_proto_init() }
func file_protos_vdr_resolver_resolver_proto_init() {
	if File_protos_vdr_resolver_resolver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vdr_resolver_resolver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveDIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vdr_resolver_resolver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveDIDRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vdr_resolver_resolver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vdr_resolver_resolver_proto_goTypes,
		DependencyIndexes: file_protos_vdr_resolver_resolver_proto_depIdxs,
		EnumInfos:         file_protos_vdr_resolver_resolver_proto_enumTypes,
		MessageInfos:      file_protos_vdr_resolver_resolver_proto_msgTypes,
	}.Build()
	File_protos_vdr_resolver_resolver_proto = out.File
	file_protos_vdr_resolver_resolver_proto_rawDesc = nil
	file_protos_vdr_resolver_resolver_proto_goTypes = nil
	file_protos_vdr_resolver_resolver_proto_depIdxs = nil
}
